### PR TITLE
enable truffle ruby in Travis CI

### PR DESCRIPTION
**Pull request by gogainda**
@eregon enabling truffle ruby support for rubyzip

### CODE REVIEW

**Comment by eregon** [comment]
```
  1) Error:
ZipFsFileNonmutatingTest#test_popen:
Errno::ENOMEM: Cannot allocate memory - posix_spawnp ls
    <internal:core> core/truffle/process_operations.rb:455:in `spawn'
    <internal:core> core/truffle/process_operations.rb:110:in `spawn'
    <internal:core> core/io.rb:894:in `popen'
    /home/travis/build/rubyzip/rubyzip/test/filesystem/file_nonmutating_test.rb:475:in `test_popen'
```

It looks like it's running out of memory while running tests.

**Comment by hainesr** [comment]
Thanks for this. Please could you add truffleruby-head to the list of tests allowed to fail? Is there a stable truffleruby version that we would more reasonably expect to always work?

**Comment by gogainda** [comment]
@eregon pls correct me if I am wrong, but we are not expecting truffleruby head to fail. It's should be as stable as "stable" version

**Comment by eregon** [comment]
@gogainda Could you try if `truffleruby` (= latest release) has the same failure?
`truffleruby-head` is fairly stable, but still it changes regularly while `truffleruby` only changes once every 3 months.
So it's up to the gem maintainers to decide if they want to test on `truffleruby`, `truffleruby-head` or both.

In any case, could you file a bug on https://github.com/oracle/truffleruby/issues about this `Errno::ENOMEM` so we can track it on TruffleRuby's side?

**Comment by hainesr** [comment]
I think we should test on both `truffleruby` and `truffleruby-head`, but let's have the head version allowed to fail in keeping with other rubies. Then the head can act as a "canary" for us without breaking the build if it does wobble. It should be allowed to wobble occasionally 😃

**Comment by gogainda** [comment]
@eregon updated

**Review by eregon — COMMENTED** [review]
Looks good to me.

**Comment by jdleesmiller** [comment]
Thanks, works for me.

**Pull request merged**
