### PR TITLE
Bzip2

### PR DESCRIPTION
**Pull request by jspanjers**

### CODE REVIEW

**Comment by hainesr** [comment]
Can I ask why you copied in the bz2 ffi stuff rather than stayed using the dependency?

**Comment by jspanjers** [comment]
> Can I ask why you copied in the bz2 ffi stuff rather than stayed using the dependency?

I started development depending on bzip2-ffi.

Afterwards I realized that I was using the private internal api from bzip2-ffi (Bzip2::FFI::Libbz2). I think it is not right to make rubyzip depend on non public api from bzip2-ffi.

I noticed that I was only using the Libbz2 ffi bindings, which are just 75 lines of code. Copying these bindings to rubyzip prevents the use of private api and also removes all dependencies on bzip2-ffi, leaving only a dependency on ffi.

**Comment by hainesr** [comment]
+1 I like/prefer the idea of a separate `rubyzip-bzip2` gem for this.

**Comment by jdleesmiller** [comment]
Closing in view of #427.

**Pull request closed without merging**
