### PR TITLE
add Ruby 3.0 to CI

### PR DESCRIPTION
**Pull request by taichi-ishitani**
This PR is to add Ruby 3.0 to CI.

### CODE REVIEW

**Comment by clarkedb** [comment]
I see this adds Ruby 3.0 to CI, but will `rubyzip` 3.0.0 be the first release that supports ruby 3.0? Or does 2.3.2 already support it?

**Comment by hainesr** [comment]
That's a good question. Our CI on the `2.x` branch died with Travis. I'll see about getting GitHub Actions backported and see where we are with that...

Thanks for raising this.

**Comment by petergoldstein** [comment]
@hainesr At this point we probably also want to add Ruby 3.1.

**Comment by hainesr** [comment]
Actions backported and confirmed that rubyzip 2.3.2 works with ruby 3.0 and 3.1. Note added to the README.

**Pull request merged**
